# Generated by Django 4.0.3 on 2022-03-25 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_rate_codigo_date_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='codigo_date_rate',
            new_name='base_rate',
        ),
    ]
