# Generated by Django 4.0.3 on 2022-03-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_codigo_date_rate_rate_base_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=3)),
                ('symbol', models.CharField(max_length=3)),
            ],
        ),
    ]
